export const management = {
  upload: {
    title: 'Upload center', subtitle: "Choose a folder and add files. Large files are uploaded in chunks, and you can keep browsing while they upload.", manageQueue: 'Manage upload queue', root: 'Root', destination: 'Upload to', destinationHint: 'Each upload keeps the storage account and folder selected when it starts, even if you change your settings later.', currentStorage: 'Current storage', storageLoading: 'Loading storage settings', queue: 'Upload queue', activeCount: '{{count}} in progress', idle: 'Idle', recoverableCount: '{{count}} ready to resume', transferPolicy: 'Upload limits', chunkThreshold: 'Files over {{size}} MiB are uploaded in chunks', limitsLoading: 'Loading upload limits', currentBatch: 'Current uploads', batchSummary: '{{completed}} completed · {{failed}} failed or cancelled', viewAll: 'View all', empty: 'Progress will appear here after you select files.',
    status: { pending: 'Waiting to upload', uploading: 'Uploading', processing: 'Processing on server', completed: 'Completed', error: 'Upload failed', cancelled: 'Cancelled' },
    reliable: { title: "Upload details", resumable: 'Resumable', resumableDetail: 'To resume an interrupted large-file upload, select the original file again.', concurrency: "Concurrent uploads", concurrencyDetail: "The queue processes up to 3 files at a time.", locked: 'Fixed destination', lockedDetail: "An upload keeps the storage account and folder chosen when it was created." },
  },
  telegramAccounts: {
    title: 'Telegram user accounts', count: 'Accounts: {{count}}', description: "Manage Telegram user accounts used for downloads. Each account’s sign-in credentials are stored separately. Disabling an account stops new task assignments but keeps its encrypted credentials.", add: 'Add account', botRequired: 'Set up the API ID and API Hash in the Telegram Bot settings before adding a user account.', retry: 'Retry', loading: 'Loading accounts…', fallbackName: 'Telegram account {{id}}', privacy: "Phone numbers and sign-in credentials are not shown in the account list. Sign-in QR codes are generated in your browser without using a third-party QR service.",
    status: { disabled: 'Disabled', ready: 'Available', cooldown: 'Cooling down', permissionDenied: 'Limited access', connecting: 'Connecting', expired: 'Session expired', error: 'Error' },
    permissions: { notChecked: 'Not checked', allowed: '{{count}} accessible', denied: '{{count}} inaccessible', unknown: '{{count}} not checked' },
    summary: { enabled: 'Enabled accounts', ready: 'Currently available', cooldown: 'Cooling down', permissions: 'Permission summary' },
    scheduling: { title: "Download scheduling", description: 'Accounts that cannot access the source, are disabled, or are cooling down are skipped. Downloads are then assigned based on each account’s scheduling weight and active download count, favoring accounts with a lower load.' },
    empty: { title: 'No Telegram user accounts linked', description: "Add an account and sign in with a QR code or phone number." },
    account: { permissions: 'Permissions', activeDownloads: 'Active downloads: {{count}}', lastChecked: 'Last checked', weight: 'Scheduling weight: {{value}}', cooldownUntil: 'Cooldown ends: {{time}}', pendingUpdate: "Awaiting update", lastError: 'Latest error', disabledHint: "Disabled: no new downloads will be assigned. Encrypted sign-in credentials are kept.", disable: 'Disable', enable: 'Re-enable', delete: 'Remove account' },
    login: { title: 'Add Telegram user account', description: 'Sign in with a QR code or phone number. Signing in by phone requires a verification code and, if enabled, your two-step verification password. Credentials are encrypted and stored only on the server.', closeAria: 'Close account setup', chooseTitle: 'Choose a sign-in method', chooseDescription: "Sign in with a QR code or phone number.", qr: 'QR code', qrDescription: 'Scan a QR code in Telegram without entering your phone number.', phone: 'Phone number', phoneDescription: 'Enter your phone number and Telegram verification code, then your two-step verification password if required.', next: 'Next', qrInstructions: 'In Telegram, open Settings → Devices → Link Desktop Device, then scan this code.', qrAria: 'Telegram sign-in QR code', generatingQr: 'Generating QR code', refreshQr: 'Refresh QR code', usePhone: 'Use phone number', back: 'Back to sign-in methods', phoneLabel: 'Phone number', phoneHint: 'Include the country or region code. The number will not be shown in the account list.', phonePlaceholder: 'For example, +1…', sendCode: 'Send code', backQr: 'Back to QR code', codeLabel: 'Verification code', codeSent: 'A verification code was sent to your Telegram app', codePlaceholder: 'Enter verification code', verify: 'Verify', passwordLabel: 'Two-step verification password', passwordHint: 'This Telegram account has two-step verification enabled. Enter its password to finish linking the account.', passwordPlaceholder: 'Enter two-step verification password', signIn: 'Sign in', completeTitle: 'Account linked and enabled', completeDescription: "Downloads are assigned by account permissions, connection status, and load.", done: 'Done' },
    errors: { qrCreate: 'Could not generate a QR code. Sign in with your phone number instead.', qrExpired: 'The QR code expired. Refresh it and scan again.', login: 'Sign-in failed. Try again.', status: 'Could not check sign-in status. Try again.', codeSend: 'Could not send the verification code', codeVerify: 'Could not verify the code', password: 'Two-step verification failed', load: 'Could not load accounts', operation: 'Account operation failed', operationTitle: 'Operation failed' },
    unlink: { message: 'Removing “{{name}}” permanently deletes its encrypted sign-in credentials from TG Vault and immediately stops assigning downloads to it.\n\nOther Telegram accounts and downloaded files are not affected.', title: 'Remove Telegram account', danger: 'This permanently deletes the account’s saved sign-in credentials and cannot be undone.', cancel: 'Keep account', confirm: 'Remove account' },
    notices: { enabled: 'Account re-enabled. Downloads can be assigned to it once it is ready.', disabled: 'Account disabled. Its encrypted sign-in credentials have been kept.', unlinked: 'Account removed from TG Vault and its saved sign-in credentials deleted.', bound: 'Account linked and enabled' },
  },
} as const;
