export const management = {
  upload: {
    title: 'Upload center', subtitle: 'Choose a destination and add files directly. Large files are chunked automatically, and uploads can continue in the background.', manageQueue: 'Manage upload queue', root: 'Root', destination: 'Upload to', destinationHint: 'The storage account and folder are locked when an upload starts and will not follow later settings changes.', currentStorage: 'Current storage', storageLoading: 'Loading storage settings', queue: 'Upload queue', activeCount: '{{count}} in progress', idle: 'Idle', recoverableCount: '{{count}} recoverable', transferPolicy: 'Transfer policy', chunkThreshold: 'Automatically chunk files over {{size}} MiB', limitsLoading: 'Loading upload limits', currentBatch: 'Current uploads', batchSummary: '{{completed}} completed · {{failed}} failed or cancelled', viewAll: 'View all', empty: 'Progress will appear here after you select files.',
    status: { pending: 'Waiting to upload', uploading: 'Uploading', processing: 'Processing on server', completed: 'Completed', error: 'Upload failed', cancelled: 'Cancelled' },
    reliable: { title: 'Reliable uploads', resumable: 'Resumable', resumableDetail: 'To resume an interrupted large-file upload, select the original file again.', concurrency: 'Controlled concurrency', concurrencyDetail: 'The queue processes up to three files at once to reduce browser and server load.', locked: 'Locked destination', lockedDetail: 'Each task records its storage account and folder when created, preventing mid-upload switching.' },
  },
  telegramAccounts: {
    title: 'Telegram user accounts', count: '{{count}} accounts', description: 'Manage the Telegram user accounts used for account-level downloads. Login credentials are isolated per account. Disabling an account pauses scheduling without signing it out.', add: 'Add account', botRequired: 'Configure the Telegram Bot API ID and API Hash before adding a user account.', retry: 'Retry', loading: 'Loading accounts…', fallbackName: 'Telegram account {{id}}', privacy: 'This page never displays phone numbers, sessions, QR-code contents, or API credentials. QR-code data is passed only to the local QR renderer.',
    status: { disabled: 'Disabled', ready: 'Available', cooldown: 'Cooling down', permissionDenied: 'Limited access', connecting: 'Connecting', expired: 'Login expired', error: 'Error' },
    permissions: { notChecked: 'Not checked', allowed: '{{count}} accessible', denied: '{{count}} inaccessible', unknown: '{{count}} pending' },
    summary: { enabled: 'Enabled accounts', ready: 'Currently available', cooldown: 'Cooling down', permissions: 'Permission summary' },
    scheduling: { title: 'Smart scheduling', description: 'The scheduler skips accounts without source access and accounts that are disabled or cooling down, then selects a lower-load account by weight and active download count.' },
    empty: { title: 'No Telegram user accounts linked', description: 'Select “Add account” and use QR login for the quickest secure setup.' },
    account: { permissions: 'Permissions', activeDownloads: 'Concurrent tasks: {{count}}', lastChecked: 'Last checked', weight: 'Scheduling weight: {{value}}', cooldownUntil: 'Cooling down until: {{time}}', pendingUpdate: 'Awaiting server update', lastError: 'Latest error', disabledHint: 'Disabled accounts do not run account-level downloads. Their encrypted login information remains stored securely.', disable: 'Disable', enable: 'Re-enable', delete: 'Delete account' },
    login: { title: 'Add Telegram user account', description: 'Sign in by QR code or phone number. Phone login requires a verification code and, when enabled, a two-step verification password. Credentials are encrypted and stored only on the server.', closeAria: 'Close account setup', chooseTitle: 'Choose a sign-in method', chooseDescription: 'Choose a method first, then start sign-in on the next step.', qr: 'QR-code login', qrDescription: 'Scan a QR code in Telegram without entering your phone number.', phone: 'Phone-number login', phoneDescription: 'Enter your phone number and Telegram verification code, then your two-step verification password if required.', next: 'Next', qrInstructions: 'In Telegram, open Settings → Devices → Link Desktop Device, then scan this code.', qrAria: 'Telegram login QR code', generatingQr: 'Generating QR code', refreshQr: 'Refresh QR code', usePhone: 'Use phone number', back: 'Back to sign-in methods', phoneLabel: 'Phone number', phoneHint: 'Include the country or region code. The number will not be shown in the account list.', phonePlaceholder: 'For example, +1…', sendCode: 'Send code', backQr: 'Back to QR login', codeLabel: 'Verification code', codeSent: 'A verification code was sent in Telegram', codePlaceholder: 'Enter verification code', verify: 'Verify', passwordLabel: 'Two-step verification password', passwordHint: 'This account has Telegram two-step verification enabled. Enter its cloud password to finish linking.', passwordPlaceholder: 'Enter two-step verification password', signIn: 'Sign in', completeTitle: 'Account linked and enabled', completeDescription: 'The account will participate in smart scheduling according to its access, health, and load.', done: 'Done' },
    errors: { qrCreate: 'Could not create a QR code. Try phone-number login instead.', qrExpired: 'The QR code expired. Refresh it and scan again.', login: 'Sign-in failed. Try again.', status: 'Could not check sign-in status. Try again.', codeSend: 'Could not send the verification code', codeVerify: 'The verification code could not be verified', password: 'Two-step verification failed', load: 'Could not load accounts', operation: 'Account operation failed', operationTitle: 'Operation failed' },
    unlink: { message: 'Deleting “{{name}}” permanently removes its encrypted login information and immediately stops it from participating in download scheduling.\n\nOther Telegram accounts and downloaded files are not affected.', title: 'Delete Telegram account', danger: 'This permanently deletes the account’s login information and cannot be undone.', cancel: 'Keep account', confirm: 'Delete account' },
    notices: { enabled: 'Account re-enabled. It will participate in scheduling when ready.', disabled: 'Account disabled. Its encrypted login information has been retained.', unlinked: 'Account and its login information deleted.', bound: 'Account linked and enabled' },
  },
} as const;
